def problem_29(n1, n2):
    """
    This function takes two values, a and b, and calculates how many
    different numbers are generated a**b with 2 <= a <= n1 and 2 <= b <= n2.
    :all_numbers: store the new values generated by a**b
    :return: return all_numbers len

    """
    
    all_numbers = []

    for a in range(2, 100+1):
        for b in range(2, 100+1):
            num = a**b
            if num not in all_numbers:
                all_numbers.append(num)
    
    return len(all_numbers)


print(problem_29(100, 100))
            


